version: '3.8'
services:
  postgresdb:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/volume:/var/lib/postgresql/data
    networks:
      - mynet
  rediscache:
    image: redis:alpine
    restart: on-failure
    ports:
      - '6379:6379'
    networks:
      - mynet
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
      - rediscache
    restart: on-failure
    networks:
      - mynet
    ports:
      - '8080:8080'
networks:
  mynet:
    driver: bridge